# Generated by Django 3.1.5 on 2021-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
